ext_clear_texture: Fix implicit-function-declaration warning.
piglit/tests/spec/ext_clear_texture/3d.c:112:2: warning: implicit declaration of function ‘init_program’ [-Wimplicit-function-declaration]
  112 |  init_program("3D");
      |  ^~~~~~~~~~~~
piglit/tests/spec/ext_clear_texture/3d.c: At top level:
piglit/tests/spec/ext_clear_texture/3d.c:205:1: warning: conflicting types for ‘init_program’
  205 | init_program();
      | ^~~~~~~~~~~~
piglit/tests/spec/ext_clear_texture/3d.c:112:2: note: previous implicit declaration of ‘init_program’ was here
  112 |  init_program("3D");
      |  ^~~~~~~~~~~~

Fixes: 398b63e54 ("ext_clear_texture: Add test for 3d textures")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Acked-by: Emma Anholt <emma@anholt.net>
Part-of: <https://gitlab.freedesktop.org/mesa/piglit/-/merge_requests/621>